# Code Security Analyzer Configuration

scanner:
  max_file_size: 10485760  # 10MB
  timeout: 300  # 5 minutes
  excluded_dirs:
    - node_modules
    - .git
    - __pycache__
    - .venv
    - build
    - dist
  excluded_files:
    - "*.pyc"
    - "*.pyo"
    - "*.so"
    - "*.dll"

report:
  format: html
  output_dir: reports
  include_source_context: true
  max_context_lines: 5

vulnerability_db:
  update_frequency: daily
  sources:
    - cve
    - npm_audit
    - pip_audit

logging:
  level: INFO
  file: logs/scanner.log
  max_size: 10485760
  backup_count: 5
